development:
  adapter: sqlite3
  encoding: utf8
  pool: 5
  timeout: 5000
  database: ":memory:"
  verbosity: quiet

codeship:
  adapter: postgresql
  encoding: unicode
  database: shoe_store
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  
production:
  url: <%= ENV['DATABASE_URL'] %>
